
ask p-(p&q)->m
ask p-(p|q)->m

ask t<-(!c)<-.

#device      d
#utilized    u
#assigned_to a
#customer    b
#ordered     o

sort 
  t.timestamp DESC
ask 
  :>-!c->*t>-a->p -- * means start query from here
  d>-u->*t
  b>-o->*t
  
return
  t p d b?

#device        d
#check_program cp

ask -- return all check programs of all devices
  d<-cp<-.

return 
  d 
  cp


ask p1-c->t 10 2
select t c
