[meta]
about   = '''
  default config file
'''

[config]

query_strategy_file_path = "./query_stategies.toml"

[config.logs]
sql = true

[config.frontend]
enabled  = true

[config.server]
host   = "0.0.0.0"
port   = 6001

[config.admin]
enabled  = true

[system]
[system.schema]
sql      = '''
  PRAGMA encoding="UTF-8";

  -- tables

  CREATE TABLE IF NOT EXISTS nodes (
      id          INTEGER PRIMARY KEY,
      tag         TEXT,
      doc         JSON NOT NULL
  );

  CREATE TABLE IF NOT EXISTS edges (
      id          INTEGER PRIMARY KEY,
      tag         TEXT,
      doc         JSON    DEFAULT '{}',
      source      INTEGER,
      target      INTEGER,

      FOREIGN KEY (source) REFERENCES nodes(id),
      FOREIGN KEY (target) REFERENCES nodes(id)
  );

  -- indexes

  CREATE INDEX IF NOT EXISTS node_index         ON nodes(id);
  CREATE INDEX IF NOT EXISTS node_tag_index     ON nodes(tag);

  CREATE INDEX IF NOT EXISTS edges_index        ON edges(id);
  CREATE INDEX IF NOT EXISTS edges_source_index ON edges(source);
  CREATE INDEX IF NOT EXISTS edges_target_index ON edges(target);
'''

