#person   p  
#acted_in a  
#movie    m

match  
  p>-a->*m

AS
  len_actors
  ()
    COUNT
    p
      .id

  collected_actor_names
  [].
    p
      .name

  is_12
  CASE
    when 
      ==
        len_actors
        12
      "YES"
    else
      "NO"

GROUP BY
  m
    .id

HAVING
  <= 
    10
    len_actors

LIMIT 
  10
OFFSET 
  1

ORDER BY
  len_actors
SORT 
  DESC

return
  {}
    "movie_title"
    m
      .title

    "has 12 actors"
    is_12

    "number_of_actors"
    len_actors

    "actors"
    collected_actor_names
