-- just wanna put my mental model of that

-- table: strcuture
-- references: relation

database
  table 
    #device d 
      program

    #person p
      name

    #task t

  references 
    #owner        o
      p>-.->d 

    #assigned_to  a
      p>-.->t

    #completed_by c 
      t>-.->p

proc 
  get_device_programs
    #device d
    insert  d
    

  get_uncompleted_tasks_of_user
    #task         t
    #completed_by c
    #assigned_to  a
    #person       p  
      ==
        .id 
        |user_id|

    match 
      *p>-a->t>-!c->p
    take  
      t
    limit 
      10
    -- group by
    order by 
      t
        .timestamp
  