[config.server]
host   = "localhost"
port   = 6001

[config.frontend]
enabled  = true

[config.users]
max_dbs = 10
needs_verification = true

[config.storage]
db_dir = "./temp/"

[config.logs]
sql      = true
req_body = true
performance = true

[config]
query_strategy_file_path = "./docs/strategies.toml"