[config.server]
host   = "localhost"
port   = 6001

[config.frontend]
enabled  = true

[config.admin]
username = "admin"
password = "1234"
enabled  = true

[config.users]
max_dbs = 10
needs_verification = true

[config.storage]
app_db_file = "./temp/app.db"
users_db_dir = "./temp/users/"
backup_dir = "./temp/backups/"

[config.logs]
sql      = true
req_body = true
performance = true

[config]
query_strategy_file_path = "./docs/strategies.toml"
open_browser = true
