[[strategies]]
key        = "single-node"
parameters = "a"
pattern    = "a"
selectable = "a"
edges      = ""
sql        = '''
  SELECT  
    |select_fields|
  FROM
    |node a|
  WHERE 
    |check_conds a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[strategies]]
key        = "single-edge-node-head"
parameters = "a b c"
pattern    = "^a>-c->b"
selectable = "a b c"
edges      = "c"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |node a|
  INNER JOIN 
    |edge c|,
    |node b|
  ON
    |check_conds c|     AND
    |check_rels c a b|
  WHERE 
    |check_conds a| AND
    |check_conds b| 

  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[strategies]]
key        = "single-edge-node-head-zero-or-more"
parameters = "a b c"
pattern    = "^a>-*c->b"
selectable = "a b c"
edges      = "c"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |node a|
  LEFT JOIN
    |edge c|
  ON 
    |check_conds c|     AND
    |check_rels  c a .|
  LEFT JOIN
    |node b|
  ON 
    |check_rels c . b| AND
    |check_conds b|
  WHERE 
    |check_conds a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[strategies]]
key        = "single-edge-node-head-inv"
parameters = "a b c"
pattern    = "^a>-!c->b"
edges      = "c"
selectable = "a"
sql        = '''
  SELECT 
    |select_fields|
  FROM   
    |node a|
  WHERE  
    |check_conds a| 
    AND NOT EXISTS 
    (
      SELECT 1
      FROM   |edge c|
      JOIN   |node b|
      ON 
        |check_conds c|    AND
        |check_rels c a b|
      WHERE 
        |check_conds b|
    )
'''

[[strategies]]
key        = "single-edge-edge"
parameters = "a b c"
pattern    = "a>-^c->b"
selectable = "a b c"
edges      = "c"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |edge c|
  INNER JOIN 
    |node a|,
    |node b|
  ON
    |check_conds a| AND
    |check_conds b| AND
    |check_rels  c a b|
  WHERE 
    |check_conds c|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[strategies]]
key        = "single-edge-node-tail"
parameters = "a b c"
pattern    = "a>-c->^b"
selectable = "a b c"
edges      = "c"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |node b|
  INNER JOIN 
    |edge c|,
    |node a|
  ON
    |check_conds a| AND
    |check_conds c| AND
    |check_rels c a b|
  WHERE
    |check_conds b|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''


[[strategies]]
key        = "2-edge"
parameters = "a b d c1 c2"
pattern    = "a<-c1-<b>-c2->d"
selectable = "a b d c1 c2"
edges      = "c1 c2"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |node b|
  JOIN 
    |node a|,
    |edge c1|
  ON
    |check_conds a| AND
    |check_conds c1| AND
    |check_rels  c1 b a|
  JOIN
    |node d|,
    |edge c2|
  ON
    |check_conds d| AND
    |check_conds c2| AND
    |check_rels  c2 b d|
  WHERE
    |check_conds b|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[strategies]]
key        = "2-nodes-2-way-inv-1"
parameters = "a b c1 c2"
pattern    = 'b>-c1->a<-!c2-<b'
selectable = "a b c1"
edges      = "c1 c2"
sql        = '''
  SELECT 
    |select_fields|
  FROM
    |node a|
  INNER JOIN 
    |edge c1|,
    |node b|
  ON
        |check_conds b|       AND
        |check_conds c1|      AND
        |check_rels  c1 a b|  AND
    NOT |exists_edge c2 a b|
  WHERE 
    |check_conds a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''
