[[q]]
pattern    = "a"
selectable = "a"
query      = '''
  SELECT 
    |select_fields|
  FROM
    nodes a
  WHERE 
    |check_node a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''


[[q]]
pattern    = "*a>-c->b"
selectable = "a b c"
query      = '''
  SELECT 
    |select_fields|
  FROM
    nodes a
  JOIN 
    edges c,
    nodes b
  ON
    |check_node b| AND
    |check_edge c a b|
  WHERE 
    |check_node a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[q]]
pattern    = "a>-*c->b"
selectable = "a b c"
query      = '''
  SELECT 
    |select_fields|
  FROM
    edges c
  JOIN 
    nodes a,
    nodes b
  ON
    |check_node a| AND
    |check_node b|
  WHERE 
    |check_edge c a b|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[q]]
pattern    = "a>-c->*b"
selectable = "a b c"
query      = '''
  SELECT 
    |select_fields|
  FROM
    nodes b
  JOIN 
    edges c,
    nodes a
  ON
    |check_node a| AND
    |check_edge c a b|
  WHERE
    |check_node b|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''

[[q]]
pattern    = "*a>-c1->b>-!c2->a"
selectable = "a b c1"
query      = '''
  SELECT 
    |select_fields|
  FROM
    nodes a
  JOIN 
    edges c1,
    nodes b
  ON
    |check_edge c1 a b|
    AND
    NOT EXISTS |exists_edge c2 a b|
  WHERE 
    |check_node a|
  |group_statement|
  |having_statement|
  |order_statement|
  |limit_statement|
  |offset_statement|
'''